toffee:
  team: "Platform Operations"
  namespace: "toffee"
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: core
toffee-shared-infrastructure:
  team: "Platform Operations"
  namespace: "toffee"
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: core
apple:
  team: "Platform Operations"
  namespace: "toffee"
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: core
apple-shared-infrastructure:
  team: "Platform Operations"
  namespace: "toffee"
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: core
pip:
  team: "Future Hearings - Publishing Information Project"
  namespace: "pip"
  slack:
    contact_channel: "#publishing-and-information"
    build_notices_channel: "#pip-build-notices"
  tags:
    application: pre-recording-evidence
hmi:
  team: "Future Hearings - Hearing Management Information"
  namespace: "hmi"
  slack:
    contact_channel: "#hearing-management-information"
    build_notices_channel: "#hmi-build-notices"
  tags:
    application: hmi
vh:
  team: "Future Hearings - Video Hearings"
  namespace: "vh"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: vh
pre:
  team: "Pre Recorded Evidence"
  namespace: "pre"
  slack:
    contact_channel: "#dts-pre-rec-evidence-tech"
    build_notices_channel: "#pre-builds"
  tags:
    application: pre
labs:
  team: "Platform Operations"
  namespace: "labs"
  slack:
    contact_channel: "#platops-labs"
    build_notices_channel: "#labs-build-notices"
  tags:
    application: core
tax-tribunals:
  team: "Tax Tribunals"
  namespace: "tt"
  slack:
    contact_channel: "#pet"
    build_notices_channel: "#pet-devops"
  tags:
    application: tax-tribunals
employment-tribunals:
  team: "Employment Tribunals"
  namespace: "et"
  slack:
    contact_channel: "#pet"
    build_notices_channel: "#pet-devops"
  tags:
    application: employment-tribunals
help-with-fees:
  team: "Help with Fees"
  namespace: "hwf"
  slack:
    contact_channel: "#pet"
    build_notices_channel: "#pet-devops"
  tags:
    application: help-with-fees
