toffee:
  team: "Platform Operations"
  namespace: "toffee"
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: core
toffee-shared-infrastructure:
  team: "Platform Operations"
  namespace: "toffee"
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: core
apple:
  team: "Platform Operations"
  namespace: "toffee"
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: core
apple-shared-infrastructure:
  team: "Platform Operations"
  namespace: "toffee"
  slack:
    contact_channel: "#platops-help"
    build_notices_channel: "#platops-build-notices"
  tags:
    application: core
pip:
  team: "Future Hearings - Publishing Information Project"
  namespace: "pip"
  slack:
    contact_channel: "#publishing-and-information"
    build_notices_channel: "#pip-build-notices"
  tags:
    application: publishing-information
hmi:
  team: "Future Hearings - Hearing Management Information"
  namespace: "hmi"
  slack:
    contact_channel: "#hearing-management-information"
    build_notices_channel: "#hmi-build-notices"
  tags:
    application: hmi
vh:
  team: "Future Hearings - Video Hearings"
  namespace: "vh"
  slack:
    contact_channel: "#vh-devops"
    build_notices_channel: "#vh-builds"
  tags:
    application: vh
